export { default as Complaint } from "./Complaint"
export { default as Pending } from "./Pending"
export { default as Completed } from "./Completed"
export { default as Deleted } from "./Deleted"
export { default as UpdateBooking } from "./updateBookings"
export { default as AgencyHome} from "./AdminHome"
export { default as AgentSignUp } from "./Agent/AgentSignUp"
